#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable

main(Args) ->
    RuntimeDir = filename:dirname(escript:script_name()),
    true = code:add_pathz(RuntimeDir ++ "/ebin"),
    erlamsa:main(Args, RuntimeDir).
