#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable

main(Args) ->
    RuntimeDir = filename:dirname(escript:script_name()),
    true = code:add_pathz(RuntimeDir ++ "/ebin"),
    true = erlamsa_utils:load_deps(RuntimeDir),
    case length([Z || Z <- Args, Z =:= "-D"]) of
        1 -> io:format("Service mode not supported for the standalone script, use erlamsa instead!~n");
        _Else -> erlamsa:main(Args)
    end.
