#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable 

%% -sname erlamsa_cmd
-mode(compile).

main(Args) -> 
	RuntimeDir = filename:dirname(escript:script_name()),
	true = code:add_pathz(RuntimeDir ++ "/ebin"),
	true = erlamsa_utils:load_deps(RuntimeDir),
    Dict = erlamsa_cmdparse:parse(Args),
	erlamsa_app:start(escript, Dict).
    
