#!/usr/bin/env escript

%% original dea and parts of code from https://github.com/cbd/edis/blob/master/priv/script_builder
%% original licence: https://github.com/cbd/edis/blob/master/LICENSE
%% original authors: https://github.com/cbd / https://inaka.github.io
%% Heavily adapted for erlamsa
%% Please inform me if I violated any licence by borrowing this code, it will be removed immedeately

load_files(Dir) ->
  [read_file(Filename, Dir) || Filename <- filelib:wildcard("*", Dir)].

read_file(Filename, Dir) ->
  {ok, Bin} = file:read_file(filename:join(Dir, Filename)),
  {Filename, Bin}.

main(_Args) ->
  true = code:add_path("ebin"),
  ok = code:add_paths(filelib:wildcard("deps/*/ebin")),
  
  Files = lists:flatmap(fun(Dir) -> load_files(Dir) end, ["ebin"|filelib:wildcard("deps/*/ebin")]),
  
  case zip:create("mem", Files, [memory]) of
    {ok, {"mem", Zip}} ->
      Script = <<"#!/usr/bin/env escript\n%%! -smp enable\n", Zip/binary>>,
      file:write_file("erlamsa", Script),
      case os:type() of
        {unix,_} ->
          os:cmd("chmod u+x erlamsa"),
          DaemonScript = <<"#!/usr/bin/env escript\n%%! -name erlamsa_app -smp enable -noshell -detached\n", Zip/binary>>,
          file:write_file("erlamsa_daemon", DaemonScript),
          [] = os:cmd("chmod u+x erlamsa_daemon"),
          ok;
        _ -> ok
      end;
    {error, Error} ->
      io:format("Cannot ZIP escript archive, error: ~p~n", [Error]),
      halt(1)
  end.
  
